import type { Metadata } from "next";
import "pretendard/dist/web/variable/pretendardvariable-dynamic-subset.css";
import "./globals.css";
import RecoilRootProvider from "@/providers/RecoilRootProvider";
import { TabStateContextProvider } from "@/contexts/TabStateContext";
import { QueryProvider } from "@/providers/query";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="ko">
      <body>
        <RecoilRootProvider>
          <QueryProvider>
            <TabStateContextProvider>{children}</TabStateContextProvider>
          </QueryProvider>
        </RecoilRootProvider>
      </body>
    </html>
  );
};

export default RootLayout;
