export const ORDER_VALIDATION_LIST_ROW_HEADERS = [
  { label: "등록상태", isRequired: false },
  { label: "배송유형", isRequired: true },
  { label: "SM명", isRequired: true },
  { label: "고객명", isRequired: true },
  { label: "주소", isRequired: true },
  { label: "운송장번호", isRequired: true },
  { label: "업체주문번호", isRequired: false },
  { label: "주문유형", isRequired: true },
  { label: "주문접수일", isRequired: true },
  { label: "작업희망일", isRequired: true },
  { label: "희망도착시간", isRequired: false },
  { label: "고객연락처", isRequired: true },
  { label: "상세주소", isRequired: true },
  { label: "우편번호", isRequired: true },
  { label: "볼륨", isRequired: true },
  { label: "중량", isRequired: true },
  { label: "고객전달사항", isRequired: false },
  { label: "예상작업시간", isRequired: false },
  { label: "상품명", isRequired: false },
  { label: "상품 코드", isRequired: false },
  { label: "상품 수량", isRequired: false },
];
